### ISSUE TITLE
Partially validate transcriptome BAM

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-rnaseq#10]
Use BAM validator function from toil-lib (https://github.com/BD2KGenomics/toil-lib/issues/37) to validate transcriptome BAM.

Consider other adding BAM validation to other pipelines, too.

**Comment by jvivian** [comment]
Blocked on BD2KGenomics/toil-lib#39

**Comment by jvivian** [comment]
toil-rnaseq now has an optionally subgraph that runs CKCC's BAM-QC
