### ISSUE TITLE
Add Pizzly

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-rnaseq#108]
- [x] Test
- [ ] Add to pipeline

**Comment by cricketsloan** [comment]
@jvivian   Can we close these?

**Comment by jvivian** [comment]
@cricketsloan — I was waiting to see if the developers were ever going to remove the need for the annotation file since it's already required to build the kallisto index and adds another input file to the workflow. They haven't, so I'll either close or merge a PR

**Comment by jvivian** [comment]
Closing unless requested in the future.
