### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-rnaseq#11]
- link to Toil at the top
- link to Toil docs' installation section
- don't mention sudo
- and, please, please, please, recommend virtualenv

**Comment by jvivian** [comment]
> and, please, please, please, recommend virtualenv

I do!

**Comment by jvivian** [comment]
Also

1. Split usage into single-machine and distributed systems
2. Link to core-operation SOP for robust distributed systems
