### ISSUE TITLE
FAIL output

### ISSUE THREAD

**Issue by moeishihara** [BD2KGenomics/toil-rnaseq#128]
We sometimes get output with "FAIL" in their folder name, but they seem to have all the result files that we're supposed to get. I would like to know what this "FAIL" header means, when we get this, and how to avoid it. Thank you.

**Comment by jvivian** [comment]
@moeishihara — Sorry for such a late reply, I'm not sure why I didn't get notified of this issue opening. 

The FAIL implies that the file failed "BamQC", which is measuring whether the sample has sufficient coverage to meet standards specified by Treehouse. This metric is a bit wishy-washy, and won't be included in the next version of the release.

For samples with a FAIL header, check FastQC to ensure that the sample doesn't have anything wrong with it that would affect downstream analysis.
