### ISSUE TITLE
Replace sortedBam output

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil-rnaseq#16]
It is hard to tell what to pass to `--limitBamSortRAM` because the ideal size depends not only on the input size but also on the read depth distribution:

https://groups.google.com/forum/#!topic/rna-star/pUIhaGda3lQ

Consider disabling the sorting in STAR and add a samtools sort step to the pipeline.

TBD: Should this fix be back-ported to 2.0.x?

**Comment by jvivian** [comment]
Closing. This issue is related to using the wrong instance size appropriate for the size of the samples being run.
