### ISSUE TITLE
AttributeError: 'Expando' object has no attribute 'bamqc'

### ISSUE THREAD

**Issue by hmkim** [BD2KGenomics/toil-rnaseq#173]
Hello!

When I turn on the save-bam option, I got the error in below.

`save-bam: true`

> WARNING:toil.leader:9/H/jobIJzf6M    Traceback (most recent call last):
> WARNING:toil.leader:9/H/jobIJzf6M      File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
> WARNING:toil.leader:9/H/jobIJzf6M        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
> WARNING:toil.leader:9/H/jobIJzf6M      File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
> WARNING:toil.leader:9/H/jobIJzf6M        returnValues = self._run(jobGraph, fileStore)
> WARNING:toil.leader:9/H/jobIJzf6M      File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
> WARNING:toil.leader:9/H/jobIJzf6M        return self.run(fileStore)
> WARNING:toil.leader:9/H/jobIJzf6M      File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/job.py", line 1480, in run
> WARNING:toil.leader:9/H/jobIJzf6M        rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
> WARNING:toil.leader:9/H/jobIJzf6M      File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil_rnaseq/toil_rnaseq.py", line 111, in workflow
> WARNING:toil.leader:9/H/jobIJzf6M        save_bam = any([config.save_bam, config.bamqc])
> WARNING:toil.leader:9/H/jobIJzf6M    AttributeError: 'Expando' object has no attribute 'bamqc'
> WARNING:toil.leader:9/H/jobIJzf6M    ERROR:toil.worker:Exiting the worker because of a failed job on host soybean
> WARNING:toil.leader:9/H/jobIJzf6M    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'workflow' 9/H/jobIJzf6M with ID 9/H/jobIJzf6M to 0
> WARNING:toil.leader:Job 'workflow' 9/H/jobIJzf6M with ID 9/H/jobIJzf6M is completely failed
> INFO:toil.leader:Finished toil run with 3 failed jobs.
> INFO:toil.leader:Failed jobs at end of the run: 'workflow' 9/H/jobIJzf6M 'workflow' s/L/jobgsFPOB 'map_job' c/Q/jobxHWc99
> Traceback (most recent call last):
>   File "/BiO/BioPeople/brandon/venv_toil/bin/toil-rnaseq", line 11, in <module>
>     sys.exit(main())
>   File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil_rnaseq/toil_rnaseq.py", line 214, in main
>     toil.start(Job.wrapJobFn(map_job, workflow, samples, config))
>   File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/common.py", line 784, in start
>     return self._runMainLoop(rootJobGraph)
>   File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
>     jobCache=self._jobCache).run()
>   File "/BiO/BioPeople/brandon/venv_toil/local/lib/python2.7/site-packages/toil/leader.py", line 237, in run
>     raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
> toil.leader.FailedJobsException

![2018-12-26 17 23 27](https://user-images.githubusercontent.com/4966343/50438861-38a79680-0933-11e9-84cd-5c044f409d23.png)

Could you check this issue ?

**Comment by jvivian** [comment]
Hi @hmkim — Is there a chance you're using an older config file with a newer version of the workflow? The newest version of the workflow has a `bamqc` option in the config that was reintroduced in version 4.1. Below the `fastqc` option you should see:

```
# If true, will run UMEND BamQC and include statistics about Uniquely Mapped Exonic Non-Duplicate (UMEND) reads
# If bamqc and save-bam are enabled, a bam with duplicates marked (output of BAMQC) is saved
bamqc: 
```

If that's not the case, please let me know so I can do some internal testing.

**Comment by hmkim** [comment]
@jvivian  Thank you. I solved this issue by your suggestion.
