### ISSUE TITLE
Use ruamel.yaml instead of pyyaml

### ISSUE THREAD

**Issue by nsjake** [BD2KGenomics/toil-rnaseq#23]

**Comment by jvivian** [comment]
Can you elaborate on this?

**Comment by hannes-ucsc** [comment]
The ruamel parser retains comments in the input, in this case the generated example config, which the wrapper then uses to populate the help strings for its command line options parser. It would be nice to only use one YAML parser in the pipeline. 

BTW: `toil[cwl]` depends on ruamel

**Comment by jvivian** [comment]
This issue is associated with a deprecated ticket.
