### ISSUE TITLE
Look into updating STAR version

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil-rnaseq#47]
@jvivian I remember we briefly looked into this already but can't remember the details, feel free to close if it isn't a good approach. 

The memory tweaks didn't solve the soft lockup bug. We know that samtools was running last time we saw this bug and that STAR is the only step that uses the samtools library, so we should see if there are newer versions of STAR with updated samtools libraries that might solve this bug.

**Comment by jvivian** [comment]
@cket — How do we test for the soft lockup? Is it readily reproducible?  I'm thinking it'd make sense to make a test branch for the toil-rnaseq pipeline where I substitute out the current container with the newest STAR version and test on that branch.  What do you think?

**Comment by cket** [comment]
We don't know how to reproduce it but it naturally occurs ~10% of the time so as soon as production starts using a new version it's pretty obvious whether it's still a problem. 

I'm assuming that newer STAR  versions have bug fixes, improvements etc. so I'm thinking it'd be a good change even if it doesn't end up fixing the soft lockup problem.

**Comment by jvivian** [comment]
@cket — The biggest issue with updating is it may make results no longer 100% concordant with results from the RNA-seq recompute.  That'd be something I'd have test. I was hoping we could run some sort of integration / scale test on the branch with the updated version to see if we see it or not.

**Comment by cket** [comment]
That works for me. It shouldn't be too difficult to show that the bug was fixed or not on the branch.

**Comment by jvivian** [comment]
Dank, I'll get on it.

**Comment by jvivian** [comment]
@cket — https://github.com/BD2KGenomics/toil-rnaseq/tree/issues/48-test-newer-star

**Comment by jvivian** [comment]
Closing in lieu of fixes in 3.3.0 which don't require an update to STAR.
