### ISSUE TITLE
Test newer STAR version for lockup issue

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil-rnaseq#48]
I'll make a branch with the newest possible STAR container for testing.

If that fixes the issue, we'll have to run concordant tests to ensure that moving to a newer version of STAR doesn't alter the results of the pipeline in any significant way.

**Comment by jvivian** [comment]
@cket - we haven't tested this yet right?

**Comment by cket** [comment]
Nope, not yet.

**Comment by jvivian** [comment]
@cket — We discussed the possibility that @jessebrennan might take over testing this if he has spare cycles.

**Comment by jvivian** [comment]
@cket — Cool if I reassign to @jessebrennan or is his bandwidth limited?

**Comment by cket** [comment]
I don't think he'll have time, IIRC during the planning meeting we discussed the possibility of @eternalnoob testing this but that's tentative right now

**Comment by jessebrennan** [comment]
I don't have time currently, but if this isn't pressing I could add it to the queue.

**Comment by jvivian** [comment]
Thanks for the update! It isn't pressing, but should probably be investigated before the SRA recompute i.e. when Azure support is wrapping up.
