### ISSUE TITLE
Document Toil log and work mount requirement for docker run command

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/toil-rnaseq#68]
The help for the Docker run command for RNA Seq does not explain that a Toil log switch such as --logDebug must be used and the work_mount switch requirement is not documented very well.

Please also provide and example of running the pipeline using docker run ...

**Comment by jvivian** [comment]
@wshands — please close if resolved.

**Comment by jvivian** [comment]
@wshands — has this been resolved?

**Comment by wshands** [comment]
Yes we added the default switch --logDebug to wrapper.py, so there is a log switch for the command if the user does not provide one.
