### ISSUE TITLE
Error when running single end read data using Docker

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/toil-rnaseq#72]
I am seeing an error when running single end read data:

        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:      DEBUG:toil.fileStore:CACHE: Released lock
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:      Traceback (most recent call last):
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:        File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:          job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:        File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:          returnValues = self._run(jobWrapper, fileStore)
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:        File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:          return self.run(fileStore)
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:        File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:          rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
        6d0c07944aef: 2017-03-27 09:15:50,407 WARNING: toil.leader: w/T/jobMdzDPw:        File "/usr/local/lib/python2.7/dist-packages/toil_rnaseq/rnaseq_cgl_pipeline.py", line
 129, in star_alignment
        6d0c07944aef: 2017-03-27 09:15:50,408 WARNING: toil.leader: w/T/jobMdzDPw:          disk = '2G' if config.ci_test else r1_id.size + r2_id.size + 80530636800  # 75 G for
 STAR index and tmp files
        6d0c07944aef: 2017-03-27 09:15:50,408 WARNING: toil.leader: w/T/jobMdzDPw:      AttributeError: 'NoneType' object has no attribute 'size'
        6d0c07944aef: 2017-03-27 09:15:50,408 WARNING: toil.leader: w/T/jobMdzDPw:      Exiting the worker because of a failed jobWrapper on host 6d0c07944aef
        6d0c07944aef: 2017-03-27 09:15:50,408 WARNING: toil.leader: w/T/jobMdzDPw:      ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host 6d0c07944aef
        6d0c07944aef: 2017-03-27 09:15:50,408 WARNING: toil.leader: w/T/jobMdzDPw:      WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 
w/T/jobMdzDPw to 0
-- 

Here is the docker command:
[job temp6635709817250157018.cwl] /datastore$ docker \
    run \
    -i \
    --volume=/var/run/docker.sock:/var/run/docker.sock:rw \
    --volume=/datastore:/datastore:rw \
    --volume=/datastore/./datastore/launcher-4036d581-fade-4ada-99d0-0bd0a82809cf/inputs/9d8089d9-fc5e-4031-9861-83e1efa16b7c/rsem_ref_hg38_no_alt.tar.gz:/var/lib/cwl/stgc207fb
ad-b505-42a1-8a82-c74f855d6586/rsem_ref_hg38_no_alt.tar.gz:ro \
    --volume=/datastore/./datastore/launcher-4036d581-fade-4ada-99d0-0bd0a82809cf/inputs/2c5570b8-83b0-410c-b79e-1826f7f3d967/TH07_0152_S01_R1.fastq.gz:/var/lib/cwl/stg26ec048f
-c185-4438-b9ed-40166a9291e6/TH07_0152_S01_R1.fastq.gz:ro \
    --volume=/datastore/./datastore/launcher-4036d581-fade-4ada-99d0-0bd0a82809cf/inputs/102a5631-3604-46d4-b08a-7bcf25159dd2/kallisto_hg38.idx:/var/lib/cwl/stg26f06f94-f681-48
cc-8110-9a7a3208df30/kallisto_hg38.idx:ro \
    --volume=/datastore/./datastore/launcher-4036d581-fade-4ada-99d0-0bd0a82809cf/inputs/a13ddf6b-12af-4938-9222-78f78a79130b/starIndex_hg38_no_alt.tar.gz:/var/lib/cwl/stg1b89c
d29-039e-4202-b968-611eef823fcf/starIndex_hg38_no_alt.tar.gz:ro \
    --volume=/datastore/datastore/launcher-4036d581-fade-4ada-99d0-0bd0a82809cf:/tmp:rw \
    --workdir=/datastore \
    --read-only=true \
    --user=0 \
    --rm \
    --env=TMPDIR=/datastore/datastore/launcher-4036d581-fade-4ada-99d0-0bd0a82809cf \
    --env=HOME=/datastore \
    quay.io/ucsc_cgl/rnaseq-cgl-pipeline:3.2.1-1 \
    --logDebug \
    --bamqc \
    --cores \
    36 \
    --kallisto \
    /var/lib/cwl/stg26f06f94-f681-48cc-8110-9a7a3208df30/kallisto_hg38.idx \
    --no-clean \
    --output-basename \
    TH07_0152_S01 \
    --resume \
    '' \
    --rsem \
    /var/lib/cwl/stgc207fbad-b505-42a1-8a82-c74f855d6586/rsem_ref_hg38_no_alt.tar.gz \
    --sample-single \
    /var/lib/cwl/stg26ec048f-c185-4438-b9ed-40166a9291e6/TH07_0152_S01_R1.fastq.gz \
    --save-bam \
    --save-wiggle \
    --star \
    /var/lib/cwl/stg1b89cd29-039e-4202-b968-611eef823fcf/starIndex_hg38_no_alt.tar.gz \
    --work_mount \
    /datastore
INFO:root:Single FASTQS to run: /var/lib/cwl/stg26ec048f-c185-4438-b9ed-40166a9291e6/TH07_0152_S01_R1.fastq.gz
INFO:root:The work mount is: /datastore
INFO:root:Pipeline input locations: 
/var/lib/cwl/stg1b89cd29-039e-4202-b968-611eef823fcf/starIndex_hg38_no_alt.tar.gz
/var/lib/cwl/stgc207fbad-b505-42a1-8a82-c74f855d6586/rsem_ref_hg38_no_alt.tar.gz
/var/lib/cwl/stg26f06f94-f681-48cc-8110-9a7a3208df30/kallisto_hg38.idx
INFO:root:Temporary directory created: /datastore/Toil-RNAseq-f9cf1329-5eb4-46f5-afc8-7d2142cd0b3c
INFO:root:Path to manifest: /datastore/Toil-RNAseq-f9cf1329-5eb4-46f5-afc8-7d2142cd0b3c
INFO:root:Docker Comand: ['toil-rnaseq', 'run', '/datastore/Toil-RNAseq-f9cf1329-5eb4-46f5-afc8-7d2142cd0b3c/jobStore', '--config', '/datastore/Toil-RNAseq-f9cf1329-5eb4-46f5-afc8-7d2142cd0b3c/toil-rnaseq.config', '--workDir', '/datastore/Toil-RNAseq-f9cf1329-5eb4-46f5-afc8-7d2142cd0b3c', '--logDebug', '--retryCount', '1', '--maxCores=36', '--manifest=/datastore/Toil-RNAseq-f9cf1329-5eb4-46f5-afc8-7d2142cd0b3c/manifest-toil-rnaseq.tsv']

**Comment by jvivian** [comment]
Thanks for the very detailed ticket @wshands — I've fixed this on an issue branch and will be pushing out a new release imminently.
