### ISSUE TITLE
Subprocess check_call Error if no logging option provided

### ISSUE THREAD

**Issue by rcurrie** [BD2KGenomics/toil-rnaseq#75]
toilLoggingOption is initialized to None:

https://github.com/BD2KGenomics/toil-rnaseq/blob/master/docker/wrapper.py#L266

and if no option is provided on the command line stays that way causing:

TypeError: execv() arg 2 must contain only strings

from subprocess.check_call as 'None' is one of the command line options. Setting --logDebug (or other) works around. Should default to something probably.

**Comment by jvivian** [comment]
@wshands - this is part of the docker wrapper, do you have bandwidth to fix this?

**Comment by rcurrie** [comment]
@wshands just logging this for future, not critical IMHO at the moment and we really can't upgrade the pipeline in production until we have an automated way to run some test files through to verify the output doesn't change (even in cases like this where it almost certainly won't change the output, but that's what tests are for...)
