### ISSUE TITLE
wrapper.py should return non zero status on failure of pipeline

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/toil-rnaseq#79]
Wrapper.py should return non zero exit code if the pipeline fails. This will enable Dockstore and Consonance to propagate failure back up the call stack.

**Comment by jvivian** [comment]
If you wanted to keep the current setup where it prints the error:
https://github.com/BD2KGenomics/toil-rnaseq/blob/master/docker/wrapper.py#L44-L48

you can just add a `raise RuntimeError` in the `else` block.
